### create a customer
POST http://localhost:8080/api/customer
Content-Type: application/json

{
  "name": "Ethan",
  "country": "CA",
  "city": "Halifax",
  "street": "6299 South St",
  "zip": "B3H4R2"
}

###
